# Generated by Django 6.0.4 on 2026-04-09 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('nm_sala', models.CharField(db_column='nm_sala', max_length=150)),
                ('qtd_capacidade', models.IntegerField(db_column='qtd_capacidade')),
                ('projetor', models.BooleanField(db_column='projetor', default=False)),
                ('tela', models.BooleanField(db_column='tela', default=False)),
                ('obs_sala', models.CharField(blank=True, db_column='obs_sala', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tb_sala',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('dth_inicio', models.DateTimeField(db_column='dth_inicio')),
                ('dth_fim', models.DateTimeField(db_column='dth_fim')),
                ('obs_reserva', models.CharField(blank=True, db_column='obs_reserva', max_length=500, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(db_column='sala_id', on_delete=django.db.models.deletion.CASCADE, to='core.room')),
            ],
            options={
                'db_table': 'tb_reserva',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nr_ramal', models.CharField(blank=True, db_column='nr_ramal', max_length=20, null=True)),
                ('nm_setor', models.CharField(blank=True, db_column='nm_setor', max_length=100, null=True)),
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_perfil_usuario',
            },
        ),
    ]
