# Generated by Django 6.0.4 on 2026-04-14 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='tp_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Aprovada'), ('R', 'Recusada')], db_column='tp_status', default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='room',
            name='acessibilidade',
            field=models.BooleanField(db_column='acessibilidade', default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='aprovador',
            field=models.ForeignKey(blank=True, db_column='aprovador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_aprovacao', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='cdg_sala',
            field=models.CharField(blank=True, db_column='cdg_sala', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='end_sala',
            field=models.CharField(blank=True, db_column='end_sala', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='exige_aprovacao',
            field=models.BooleanField(db_column='exige_aprovacao', default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='nm_predio',
            field=models.CharField(blank=True, db_column='nm_predio', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='nr_andar',
            field=models.CharField(blank=True, db_column='nr_andar', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='quadro_branco',
            field=models.BooleanField(db_column='quadro_branco', default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='videoconferencia',
            field=models.BooleanField(db_column='videoconferencia', default=False),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('mensagem', models.CharField(db_column='mensagem', max_length=255)),
                ('lido', models.BooleanField(db_column='lido', default=False)),
                ('dth_criacao', models.DateTimeField(auto_now_add=True, db_column='dth_criacao')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, related_name='notificacoes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_notificacao',
            },
        ),
    ]
