# Generated by Django 6.0.4 on 2026-04-14 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_reservation_tp_status_room_acessibilidade_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='acessibilidade',
            field=models.BooleanField(db_column='acessibilidade', default=False, verbose_name='Possui Acessibilidade'),
        ),
        migrations.AlterField(
            model_name='room',
            name='aprovador',
            field=models.ForeignKey(blank=True, db_column='aprovador_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_aprovacao', to=settings.AUTH_USER_MODEL, verbose_name='Aprovador Responsável'),
        ),
        migrations.AlterField(
            model_name='room',
            name='cdg_sala',
            field=models.CharField(blank=True, db_column='cdg_sala', max_length=50, null=True, verbose_name='Identificação (Código)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='end_sala',
            field=models.CharField(blank=True, db_column='end_sala', max_length=255, null=True, verbose_name='Endereço Completo'),
        ),
        migrations.AlterField(
            model_name='room',
            name='exige_aprovacao',
            field=models.BooleanField(db_column='exige_aprovacao', default=False, verbose_name='Exige Aprovação'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nm_predio',
            field=models.CharField(blank=True, db_column='nm_predio', max_length=150, null=True, verbose_name='Nome do Prédio'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nm_sala',
            field=models.CharField(db_column='nm_sala', max_length=150, verbose_name='Nome da Sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='nr_andar',
            field=models.CharField(blank=True, db_column='nr_andar', max_length=50, null=True, verbose_name='Número do Andar'),
        ),
        migrations.AlterField(
            model_name='room',
            name='obs_sala',
            field=models.CharField(blank=True, db_column='obs_sala', max_length=255, null=True, verbose_name='Observações da Sala'),
        ),
        migrations.AlterField(
            model_name='room',
            name='projetor',
            field=models.BooleanField(db_column='projetor', default=False, verbose_name='Possui Projetor'),
        ),
        migrations.AlterField(
            model_name='room',
            name='qtd_capacidade',
            field=models.IntegerField(db_column='qtd_capacidade', verbose_name='Capacidade (Qtd)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='quadro_branco',
            field=models.BooleanField(db_column='quadro_branco', default=False, verbose_name='Possui Quadro Branco'),
        ),
        migrations.AlterField(
            model_name='room',
            name='tela',
            field=models.BooleanField(db_column='tela', default=False, verbose_name='Possui Tela'),
        ),
        migrations.AlterField(
            model_name='room',
            name='videoconferencia',
            field=models.BooleanField(db_column='videoconferencia', default=False, verbose_name='Possui Videoconferência'),
        ),
    ]
